server:
  port: 5678
#  servlet:
#    context-path: /planeAndWeatherApp
  address: 0.0.0.0
spring:
  application:
    name: agent-sample-with-mcp
ai:
  bridge:
    zhipu:
      api_key: your_key
  mcp:
    getRealWeatherInfo:
      tool-name: getRealWeatherInfo
      base-url: http://localhost:8080
      api-key: your_key
    calculate:
      tool-name: calculate
      base-url: http://localhost:8080
      api-key: your_key
    queryAllValidWeatherLocation:
      tool-name: queryAllValidWeatherLocation
      base-url: http://localhost:8080
      api-key: your_key